# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Jacob Sansbury: Software Engineer"
email: "jacob(@)workbyjacob(.)com"
description: "A Software Engineer's musing about technology and the way it shapes our lives."
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://workbyjacob.com" # The base hostname & protocol for your site
twitter: "https://twitter.com/jacob_sansbury"
github: "https://github.com/jsnns"

markdown: kramdown
permalink: pretty
paginate: 60

sass:
   style: compressed

plugins:
   - jekyll-paginate
   - jekyll/tagging
   - jekyll-sitemap
   - jekyll-minifier

include:
   - _pages

exclude:
   - vendor
   - Gemfile
   - Gemfile.lock
   - run

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# Pages path
defaults:
   - scope:
        path: "_pages"
     values:
        permalink: /:basename:output_ext
